services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring-config/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ./prometheus-data:/prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring-config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager-data:/alertmanager

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring-config/loki.yml:/etc/loki/loki.yml
      - ./loki-data:/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - ./monitoring-config/promtail.yml:/etc/promtail/promtail.yml
      - /var/log:/var/log

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "9095:9095"
    volumes:
      - ./monitoring-config/tempo.yml:/etc/tempo/tempo.yml
      - ./tempo-data:/tmp/tempo/data
    command:
      - -config.file=/etc/tempo/tempo.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
    volumes:
      - ./grafana-data:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"

  blackbox_exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./monitoring-config/blackbox.yml:/etc/blackbox_exporter/config.yml

  aws_cloudwatch_exporter:
    image: prom/cloudwatch-exporter:latest
    container_name: aws_cloudwatch_exporter
    ports:
      - "9106:9106"
    volumes:
      - ./monitoring-config/aws_exporter.yml:/config.yml
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    command:
      - --config.file=/config.yml


