global:
  scrape_interval: 15s

rule_files:
  - prometheus_rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: ['blackbox_exporter:9115']

  - job_name: 'website_probes'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://aimavs.com
        - https://matchbest.ai
        - https://matchbestsoftware.com
        - https://maverickservices.in
        - https://elitemaverick.com
        - https://ai.aimavs.com
        - https://careercloudhub.com
        - https://mamacrunchexport.com
        - https://ava.matchbestsoftware.com
        - https://mamacrunchglobal.com
        - https://maverickelitetech.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
